# Generated by Django 4.1.7 on 2023-03-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0002_todo_todo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='todo_status',
            field=models.CharField(default='In progress', max_length=200),
        ),
    ]
