# Generated by Django 4.1.7 on 2023-03-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0003_todo_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo_status',
            field=models.CharField(default='In progress', max_length=100),
        ),
    ]
